-- ============================================================
-- DEEDS. daily seed
-- Run AFTER deeds-patch-11.sql. Rerunnable: it only inserts
-- when daily_prompts is empty, and overrides upsert by date.
--
-- 120 acts in the house voice. The rotation repeats about
-- every four months; dated overrides always win. Append more
-- prompts any time to lengthen the cycle (appending shifts
-- future days only, never past numbers, which are already
-- stamped on logged deeds).
-- ============================================================

do $$
begin
  if (select count(*) from public.daily_prompts) > 0 then
    raise notice 'daily_prompts already seeded, skipping';
    return;
  end if;

  insert into public.daily_prompts (act) values
  ('Pay for the order behind you.'),
  ('Write a thank you note to someone who never got one.'),
  ('Carry it in for them.'),
  ('Let the car merge. Wave.'),
  ('Tip double. Say nothing.'),
  ('Text an old friend the memory you still laugh about.'),
  ('Leave the five star review the small shop deserves.'),
  ('Return the cart. Take a stray one with you.'),
  ('Bring the extra coffee.'),
  ('Tell their manager they were great. Use their name.'),
  ('Buy flowers. Give them to the third person you pass.'),
  ('Let the person with two items go ahead.'),
  ('Call, do not text, the one who lives alone.'),
  ('Tell someone what you learned from them.'),
  ('Compliment a stranger on something they chose, not something they are.'),
  ('Hold the elevator. Every time today.'),
  ('Give up your seat before anyone has to ask.'),
  ('Do the chore that is not yours. Say nothing.'),
  ('Learn the name you have been faking. Use it.'),
  ('Bake double. Deliver half warm.'),
  ('Pick up ten pieces of litter you did not drop.'),
  ('Donate the coat you kept for the person you used to be.'),
  ('Drop a book in the little library. Your favorite, not your spare.'),
  ('Buy from the kid''s stand. Overpay.'),
  ('Thank the person who cleans. They hear it least.'),
  ('Ask the quiet one what they think. Wait for the answer.'),
  ('Cover the shift. Do not collect.'),
  ('Forward the job posting to the person it fits.'),
  ('Stay ten minutes and help them finish.'),
  ('Ask the oldest person you know for a story. Write it down.'),
  ('Do the dishes at someone else''s house.'),
  ('Play the game the kid picks. Full effort.'),
  ('Say sorry first. Even if you are half right.'),
  ('Frame the photo. Give it.'),
  ('Take the middle seat.'),
  ('Park far. Leave the close ones.'),
  ('Tape a dollar to the vending machine.'),
  ('Round up for the charity at the register. Every register today.'),
  ('Buy two. Give one away.'),
  ('Leave your change in the tip jar. All of it.'),
  ('Send a friend an old photo of a good day.'),
  ('Tell your parents one specific thing they got right.'),
  ('Praise someone to a person who can promote them.'),
  ('Tell the cook it was the best one yet.'),
  ('Leave a kind note on a windshield. Sign it with nothing.'),
  ('Answer the message you have been putting off. Kindly.'),
  ('Thank a teacher who is still teaching. Or one who is done.'),
  ('Write down three things someone does right. Hand over the list.'),
  ('Sit with someone eating alone. Ask first.'),
  ('Teach someone the thing they keep asking about.'),
  ('Show up early and set up. Leave late and tear down.'),
  ('Walk the neighbor''s bins up the drive.'),
  ('Sweep past your property line.'),
  ('Offer your umbrella. Mean it.'),
  ('Give someone your full attention. Phone in the other room.'),
  ('Drive the long way so they get door to door.'),
  ('Bring the extra plate to the neighbor.'),
  ('Check on the porch light that has been off all week.'),
  ('Water something that is not yours.'),
  ('Offer to grab groceries for the one who cannot drive.'),
  ('Introduce two neighbors who should know each other.'),
  ('Put the fallen bin back before they see it.'),
  ('Take the meeting note nobody wants to take.'),
  ('Give the credit away. Specifically.'),
  ('Bring coffee for the whole row.'),
  ('Train the new one like they will outgrow you.'),
  ('Fix the thing your parents stopped mentioning.'),
  ('Tell your sibling the thing you admire and never said.'),
  ('Give blood. Bring a friend who is scared.'),
  ('Sign up for the volunteer slot nobody filled.'),
  ('Thank the crossing guard. Learn the name.'),
  ('Bring the food bank protein and diapers. They never have enough.'),
  ('Return the library books with a thank you card inside.'),
  ('Go to the local game. Cheer for both sides.'),
  ('Thank a veteran with a question, not a slogan. Then listen.'),
  ('Pay for the uniform''s meal. Any uniform.'),
  ('Send a card to a veterans home. No occasion.'),
  ('Bring the night shift something warm.'),
  ('Fill something with water and set it out for the birds.'),
  ('Offer to walk the dog of someone stretched thin.'),
  ('Donate old towels to the shelter. They always need towels.'),
  ('Plant something that outlives the season.'),
  ('Forgive the small debt. Tell them it is settled.'),
  ('Say a prayer, or hold a good thought, for the hardest person in your life.'),
  ('Fast from complaining until dinner. Give the energy away instead.'),
  ('Apologize without the word but.'),
  ('Send the article to the one person it will actually help.'),
  ('Answer the forum question you once asked.'),
  ('Share the small creator''s work where people will see it.'),
  ('Delete the mean comment you drafted. Write nothing.'),
  ('Leave the tutorial maker a thank you. They never hear back.'),
  ('Stock the office fridge with the good stuff. Anonymously.'),
  ('Leave the babysitter a real tip.'),
  ('Buy the teacher''s wishlist item. The whole class gets it.'),
  ('Tape a gift card where someone will find it. Write: for you.'),
  ('Make two lunches. Give one to someone who needs it.'),
  ('Keep granola bars in the car. Hand one out the window.'),
  ('Offer your place in line at the pharmacy.'),
  ('Bring donuts to the longest line in town.'),
  ('Take the smaller half.'),
  ('Tip where there is no jar.'),
  ('Cheer loudest for the last finisher.'),
  ('Tell a new parent they are doing fine. Say exactly how.'),
  ('Tell the person training for it that they will make it.'),
  ('Write the recommendation before they ask.'),
  ('Show up to the thing they invited you to. The small one.'),
  ('Ask for the story behind the name. Listen twice as long.'),
  ('Learn to say thank you in the language of the person who serves you lunch.'),
  ('Leave your book on the bench with a note: it is yours now.'),
  ('Make the introduction you keep meaning to make.'),
  ('Tell someone: I thought of you today. Then tell them why.'),
  ('Let someone else pick. Enjoy it anyway.'),
  ('Return what you borrowed, cleaner than you got it.'),
  ('Put your phone away at the register and say hello.'),
  ('Leave the last one for the next person.'),
  ('Write down what someone taught you and send it to them.'),
  ('Invite the one who is always almost invited.'),
  ('Do the errand they keep postponing. Quietly.'),
  ('Tell the story that makes someone else the hero.'),
  ('Thank someone for something they did years ago.');

end $$;

-- Dated overrides. These win over the rotation on their day.
insert into public.daily_overrides (on_date, act) values
  (date '2026-11-26', 'Thank the person who cooked. Specifically.'),
  (date '2026-12-24', 'Leave something for the driver still delivering tonight.'),
  (date '2026-12-25', 'Give a gift nobody will ever know came from you.'),
  (date '2027-01-01', 'Send the Forty to one person. Their year starts today.'),
  (date '2027-02-10', 'Do a hidden deed. Tell no one. That was always the point.'),
  (date '2027-02-14', 'Do something loving for someone who is not your valentine.'),
  (date '2027-03-28', 'Set a place for someone who would otherwise eat alone.')
on conflict (on_date) do update set act = excluded.act;
